name: Release

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  BINARY_NAME: yanimator

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: yanimator-linux-x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: yanimator_windows.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: yanimator-macos-x86_64

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare asset for upload
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          cp ${{ matrix.artifact_name }} ../../${{ matrix.artifact_name }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
